Vagrant.configure("2") do |config|
    config.vm.define "alma-web1" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.121"
        config.vm.synced_folder "shared/", "/vagrant"

        machine.vm.disk :disk, size: "3GB", name: "sdb"
        machine.vm.disk :disk, size: "3GB", name: "sdc"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-web1
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/raid-setup.sh
            bash /vagrant/glusterfs-setup.sh
            bash /vagrant/web-setup.sh
            bash /vagrant/setup-monitoring.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-web2" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.122"
        config.vm.synced_folder "shared/", "/vagrant"

        machine.vm.disk :disk, size: "3GB", name: "sdb"
        machine.vm.disk :disk, size: "3GB", name: "sdc"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-web2
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/raid-setup.sh
            bash /vagrant/glusterfs-setup.sh
            bash /vagrant/web-setup.sh
            bash /vagrant/setup-monitoring.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-sql1" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.111"
        machine.vm.synced_folder "shared/", "/vagrant"

        machine.vm.disk :disk, size: "3GB", name: "sdb"
        machine.vm.disk :disk, size: "3GB", name: "sdc"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
            vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-sql1
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/raid-setup.sh
            bash /vagrant/glusterfs-setup.sh
            bash /vagrant/setup-monitoring.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-sql2" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.112"
        machine.vm.synced_folder "shared/", "/vagrant"

        machine.vm.disk :disk, size: "3GB", name: "sdb"
        machine.vm.disk :disk, size: "3GB", name: "sdc"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
            vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-sql2
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/raid-setup.sh
            bash /vagrant/glusterfs-setup.sh
            bash /vagrant/setup-monitoring.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-haproxy1" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "172.20.32.200"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.100"
        machine.vm.synced_folder "shared/", "/vagrant"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
            vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-haproxy1
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/haproxy-setup.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-haproxy2" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "172.20.32.201"
        machine.vm.network "private_network", type: "static", ip: "192.168.32.101"
        machine.vm.synced_folder "shared/", "/vagrant"

        machine.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]
            vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-haproxy2
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/haproxy-setup.sh
            sudo reboot
        SHELL
    end

    config.vm.define "alma-client" do |machine|
        machine.vm.box = "0x1eo/alma"
        config.vm.box_version = "1.0.0"
        machine.vm.network "private_network", type: "static", ip: "172.20.32.10"
        machine.vm.synced_folder "shared/", "/vagrant"
            
        machine.vm.provision "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--groups", "/TPSC"]  
        end

        machine.vm.provision "shell", inline: <<-SHELL
            sudo hostnamectl set-hostname alma-client
            chmod +x /vagrant/*.sh
            bash /vagrant/initial-setup.sh
            bash /vagrant/gui.sh
            sudo reboot
        SHELL
    end
end